# Generated by Django 5.0.6 on 2024-07-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
