# Generated by Django 5.0.6 on 2024-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access",
            field=models.CharField(default="patient", max_length=100),
        ),
    ]
