# Generated by Django 5.0.6 on 2024-07-26 02:28

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="fallback.png",
                upload_to=users.models.user_profile_path,
            ),
        ),
    ]
