# Generated by Django 5.0.6 on 2024-06-25 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
