# Generated by Django 5.0.6 on 2024-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="DOB",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blood_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.SmallIntegerField(null=True),
        ),
    ]
