# Generated by Django 5.0.6 on 2024-07-26 02:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="user_profiles/fallback.png",
                upload_to=users.models.user_profile_path,
            ),
        ),
    ]
