# Generated by Django 5.0.6 on 2024-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_dob_user_blood_type_user_height_user_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="blood_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
