# Generated by Django 5.0.6 on 2024-06-27 16:05

from django.db import migrations

def add_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={
            'domain': '127.0.0.1:8000',
            'name': 'healthharmony'
        }
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_dob_alter_user_blood_type_and_more"),
    ]

    operations = [
        migrations.RunPython(add_site),
    ]
