services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - redis
    volumes:
      - ./app:/usr/src/app

  redis:
    image: redis:latest
    ports:
    - '6379:6379'
