version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./app:/usr/src/app
    network_mode: host  # Use host network mode

  redis:
    image: redis:latest
    network_mode: host  # Use host network mode
