services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/usr/src/app

  redis:
    image: redis:latest
    ports:
    - '6379:6379'

  db:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=12345678
    ports:
    - '5432:5432'
