version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - redis
    volumes:
      - ./app:/usr/src/app
    network_mode: host  # Use host network mode

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    network_mode: host  # Use host network mode
