# Generated by Django 5.0.6 on 2024-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illness",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
