# Generated by Django 5.0.6 on 2024-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illness",
            name="added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="illness",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
