# Generated by Django 5.0.6 on 2024-07-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illness",
            name="illness_category",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="illness_category",
                to="treatment.category",
            ),
        ),
    ]
