# Generated by Django 5.0.6 on 2024-07-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordetail",
            name="time_avail",
            field=models.DurationField(null=True),
        ),
    ]
