# Generated by Django 5.0.6 on 2024-07-15 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0003_alter_illnesstreatment_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="illness",
            options={"ordering": ["-added"]},
        ),
    ]
