# Generated by Django 5.0.6 on 2024-07-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0003_alter_illness_illness_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illness",
            name="illness_category",
            field=models.ManyToManyField(
                blank=True, related_name="illness_category", to="treatment.category"
            ),
        ),
    ]
