# Generated by Django 5.0.6 on 2024-07-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0003_doctordetail_time_avail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctordetail",
            name="time_avail",
        ),
        migrations.AddField(
            model_name="doctordetail",
            name="time_avail_end",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="doctordetail",
            name="time_avail_start",
            field=models.TimeField(null=True),
        ),
    ]
