# Generated by Django 5.0.6 on 2024-07-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0004_alter_illness_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="requested",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
