# Generated by Django 5.0.6 on 2024-07-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0006_alter_doctordetail_time_avail_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetail",
            name="time_avail_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="doctordetail",
            name="time_avail_start",
            field=models.DateTimeField(null=True),
        ),
    ]
