# Generated by Django 5.0.6 on 2024-09-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambulansya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_avail", models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
