# Generated by Django 5.0.6 on 2024-09-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bed", "0002_ambulansya"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelChair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
