# Generated by Django 5.0.6 on 2024-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bed", "0003_wheelchair"),
    ]

    operations = [
        migrations.AddField(
            model_name="wheelchair",
            name="is_avail",
            field=models.BooleanField(default=False),
        ),
    ]
