# Generated by Django 5.0.6 on 2024-07-09 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_no", models.SmallIntegerField(default=None)),
                ("unit", models.CharField(max_length=100, null=True)),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("expiration_date", models.DateField(default=None)),
                ("orig_quantity", models.SmallIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="QuantityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_created=True)),
                ("updated_quantity", models.PositiveIntegerField()),
                (
                    "inventory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventorydetail",
                    ),
                ),
            ],
        ),
    ]
