# Generated by Django 5.0.6 on 2024-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("item_no", models.BigAutoField(primary_key=True, serialize=False)),
                ("unit", models.CharField(blank=True, max_length=100)),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("expiration_date", models.DateField(default=None)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
    ]
