# Generated by Django 5.0.6 on 2024-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorydetail",
            name="orig_quantity",
        ),
        migrations.AlterField(
            model_name="quantityhistory",
            name="updated_quantity",
            field=models.IntegerField(),
        ),
    ]
