# Generated by Django 5.0.6 on 2024-07-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_inventorydetail_orig_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorydetail",
            name="category",
            field=models.CharField(
                choices=[("medicine", "Medicine"), ("supply", "Supply")],
                default="Medicine",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inventorydetail",
            name="item_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="inventorydetail",
            name="unit",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
