# Generated by Django 5.0.6 on 2024-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_quantityhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorydetail",
            name="quantity",
        ),
    ]
