# Generated by Django 5.0.6 on 2024-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_inventorydetail_added_by_quantityhistory_changed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorydetail",
            name="expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
