# Generated by Django 5.0.6 on 2024-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_inventorydetail_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quantityhistory",
            old_name="less",
            new_name="updated_quantity",
        ),
        migrations.AddField(
            model_name="inventorydetail",
            name="orig_quantity",
            field=models.SmallIntegerField(default=None),
        ),
    ]
