# Generated by Django 5.0.6 on 2024-06-20 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_rename_less_quantityhistory_updated_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorydetail",
            name="orig_quantity",
        ),
    ]
