# Generated by Django 5.0.6 on 2024-06-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_remove_inventorydetail_orig_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorydetail",
            name="orig_quantity",
            field=models.SmallIntegerField(default=None),
        ),
    ]
