# Generated by Django 5.0.6 on 2024-10-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_file", models.BinaryField()),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ModelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trained_models.models",
                    ),
                ),
            ],
            options={
                "ordering": ["-update_time"],
            },
        ),
    ]
