# Generated by Django 5.0.6 on 2024-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trained_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="models",
            name="model_file",
            field=models.BinaryField(),
        ),
    ]
