# Generated by Django 5.0.6 on 2024-07-19 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={"ordering": ["-timestamp"]},
        ),
    ]
