# Generated by Django 5.0.6 on 2024-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datachangelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("Create", "Create"),
                    ("Update", "Update"),
                    ("Delete", "Delete"),
                ],
                max_length=10,
            ),
        ),
    ]
