# Generated by Django 5.0.6 on 2024-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=30, null=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-update_time"],
            },
        ),
    ]
