# Generated by Django 5.0.6 on 2024-08-05 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modellog",
            options={"ordering": ["update_time"]},
        ),
    ]
