# Generated by Django 5.0.6 on 2024-08-30 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelLog",
        ),
    ]
