# Generated by Django 5.0.6 on 2024-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bedstat",
            name="status",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
