# Generated by Django 5.0.6 on 2024-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="illnesstreatment",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
