# Generated by Django 5.0.6 on 2024-09-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
