# Generated by Django 5.0.6 on 2024-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
