# Generated by Django 5.0.6 on 2024-09-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0003_alter_illnesstreatment_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
