# Generated by Django 5.0.6 on 2024-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0004_certificate_is_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetail",
            name="avail",
            field=models.BooleanField(default=True),
        ),
    ]
