# Generated by Django 5.0.6 on 2024-09-16 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0005_alter_doctordetail_avail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["-requested"]},
        ),
    ]
