# Generated by Django 5.0.6 on 2024-09-17 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment", "0006_alter_certificate_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="illnessnote",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="illness_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
